-- Migration: Add AI Audit Tables
-- This migration adds tables for AI action logging and tool execution tracking

-- AI Audit Log Table
CREATE TABLE IF NOT EXISTS ai_audit_log (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES labour(id) ON DELETE SET NULL,
  session_id VARCHAR(255),
  transcript TEXT NOT NULL,
  intent VARCHAR(100),
  confidence DECIMAL(5, 4),
  entities JSONB,
  tool_calls JSONB,
  executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- AI Tool Execution Log Table
CREATE TABLE IF NOT EXISTS ai_tool_execution_log (
  id SERIAL PRIMARY KEY,
  audit_log_id INTEGER REFERENCES ai_audit_log(id) ON DELETE CASCADE,
  tool_name VARCHAR(100) NOT NULL,
  parameters JSONB,
  success BOOLEAN NOT NULL,
  result JSONB,
  error_message TEXT,
  execution_time_ms INTEGER,
  executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_ai_audit_log_user_id ON ai_audit_log(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_audit_log_session_id ON ai_audit_log(session_id);
CREATE INDEX IF NOT EXISTS idx_ai_audit_log_executed_at ON ai_audit_log(executed_at);
CREATE INDEX IF NOT EXISTS idx_ai_tool_execution_log_audit_log_id ON ai_tool_execution_log(audit_log_id);
CREATE INDEX IF NOT EXISTS idx_ai_tool_execution_log_tool_name ON ai_tool_execution_log(tool_name);
CREATE INDEX IF NOT EXISTS idx_ai_tool_execution_log_executed_at ON ai_tool_execution_log(executed_at);

-- Add comments for documentation
COMMENT ON TABLE ai_audit_log IS 'Audit log for AI voice assistant actions';
COMMENT ON TABLE ai_tool_execution_log IS 'Execution log for AI tool calls';
COMMENT ON COLUMN ai_audit_log.transcript IS 'User voice transcript';
COMMENT ON COLUMN ai_audit_log.intent IS 'Detected intent from AI';
COMMENT ON COLUMN ai_audit_log.confidence IS 'AI confidence score (0-1)';
COMMENT ON COLUMN ai_audit_log.entities IS 'Extracted entities as JSON';
COMMENT ON COLUMN ai_audit_log.tool_calls IS 'Tool calls generated by AI';
COMMENT ON COLUMN ai_tool_execution_log.execution_time_ms IS 'Tool execution time in milliseconds';