import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import aiRouter from "./ai.js";
import aiEnhancedRouter from "./ai-enhanced.js";
import authRouter from "./auth.js";
import projectsRouter from "./projects.js";
import labourRouter from "./labour.js";
import masonRouter from "./mason.js";
import attendanceRouter from "./attendance.js";
import masonAttendanceRouter from "./mason-attendance.js";
import expensesRouter from "./expenses.js";
import materialsRouter from "./materials.js";
import equipmentRouter from "./equipment.js";
import paymentsRouter from "./payments.js";
import masonPaymentsRouter from "./mason-payments.js";
import diaryRouter from "./diary.js";
import photosRouter from "./photos.js";
import reportsRouter from "./reports.js";
import backupRouter from "./backup.js";
import settingsRouter from "./settings.js";
import remindersRouter from "./reminders.js";
import toolsRouter from "./tools.js";
import { authenticate } from "../middlewares/auth.js";
import { aiAuthMiddleware, aiRateLimitMiddleware, aiRequestValidationMiddleware } from "../middlewares/ai-auth.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/ai", aiRouter);
router.use("/ai/v2", aiAuthMiddleware, aiRateLimitMiddleware, aiRequestValidationMiddleware, aiEnhancedRouter);
router.use("/auth", authRouter);
router.use("/tools", authenticate, toolsRouter);
router.use("/projects", authenticate, projectsRouter);
router.use("/labour", authenticate, labourRouter);
router.use("/mason", authenticate, masonRouter);
router.use("/attendance", authenticate, attendanceRouter);
router.use("/mason-attendance", authenticate, masonAttendanceRouter);
router.use("/expenses", authenticate, expensesRouter);
router.use("/materials", authenticate, materialsRouter);
router.use("/equipment", authenticate, equipmentRouter);
router.use("/payments", authenticate, paymentsRouter);
router.use("/mason-payments", authenticate, masonPaymentsRouter);
router.use("/diary", authenticate, diaryRouter);
router.use("/photos", authenticate, photosRouter);
router.use("/reports", authenticate, reportsRouter);
router.use("/backup", authenticate, backupRouter);
router.use("/settings", authenticate, settingsRouter);
router.use("/reminders", remindersRouter);

export default router;
